### ISSUE TITLE
Looking for contacts in France

### ISSUE THREAD

**Issue by phanhuynh** [datajoint/element-calcium-imaging#119]
Hello everyone, I'm about to start installing DJ for a calcium imaging project based in Marseille, France (https://www.univ-amu.fr/en/node/6220).  Does anyone know of any teams in France that has already done this?  Thank you so much!

**Comment by kabilar** [comment]
Hi @phanhuynh, it is nice to meet you.  There are likely users in France, but I am not aware of them.  You could reach out directly to our community on [Slack](https://join.slack.com/t/datajoint/shared_invite/zt-3pioa7mu-R_G_z07arbgLelDuDxotdg) to see if there are users in France.  Our list of known teams who are using DataJoint is [here](https://datajoint.com/docs/projects/).  Since you are getting started, I would be happy to meet with you to review your project needs and how the DataJoint ecosystem of tools would work for your project ([scheduling link](https://calendly.com/d/yjh-hsx-bjc/datajoint-users)).  Thank you.

**Comment by dimitri-yatsenko** [comment]
Not sure if it helps, but there are many users in Germany. In fact, we are going to give a workshop at Bonn University ~March 23 if you would like to join.

**Comment by kabilar** [comment]
Hi @phanhuynh, thanks for joining Slack.  Feel free to reach out if you have any questions as you get your pipeline running.  Closing this issue for now.
